import { Item, Category, Relevance } from './types.ts';

// FIX: Changed Omit type from 'completed' to 'completedQuantity' to match the Item interface and the intended usage.
export const initialItems: Omit<Item, 'id' | 'completedQuantity' | 'completedBy' | 'createdAt' | 'completedAt'>[] = [
  // LAVANDERIA
  { name: 'Lavadora secadora', category: Category.LAUNDRY, relevance: Relevance.HIGH, price: 450000, quantity: 1 },
  { name: 'Repisa para detergentes', category: Category.LAUNDRY, relevance: Relevance.LOW, price: 25000, quantity: 1 },
  { name: 'Colgador plegable', category: Category.LAUNDRY, relevance: Relevance.HIGH, price: 30000, quantity: 1 },
  { name: 'Plancha', category: Category.LAUNDRY, relevance: Relevance.MEDIUM, price: 20000, quantity: 1 },
  { name: 'Tabla de Planchar', category: Category.LAUNDRY, relevance: Relevance.LOW, price: 25000, quantity: 1 },
  { name: 'Ganchos para ropa', category: Category.LAUNDRY, relevance: Relevance.HIGH, price: 10000, quantity: 1 },
  { name: 'Canasto ropa sucia', category: Category.LAUNDRY, relevance: Relevance.HIGH, price: 15000, quantity: 1 },
  { name: 'Canasto ropa limpia', category: Category.LAUNDRY, relevance: Relevance.HIGH, price: 15000, quantity: 1 },
  { name: 'Cortina Roller', category: Category.LAUNDRY, relevance: Relevance.HIGH, price: 40000, quantity: 1 },
  // COCINA
  { name: 'Refrigerador', category: Category.KITCHEN, relevance: Relevance.HIGH, price: 500000, quantity: 1 },
  { name: 'Microondas', category: Category.KITCHEN, relevance: Relevance.MEDIUM, price: 70000, quantity: 1 },
  { name: 'Hervidor electrico', category: Category.KITCHEN, relevance: Relevance.HIGH, price: 20000, quantity: 1 },
  { name: 'Juego de Ollas', category: Category.KITCHEN, relevance: Relevance.HIGH, price: 80000, quantity: 1 },
  { name: 'Sarten grande', category: Category.KITCHEN, relevance: Relevance.MEDIUM, price: 25000, quantity: 1 },
  { name: 'Sarten pequeno', category: Category.KITCHEN, relevance: Relevance.HIGH, price: 15000, quantity: 1 },
  { name: 'Fuente de vidrio (budinera)', category: Category.KITCHEN, relevance: Relevance.LOW, price: 12000, quantity: 1 },
  { name: 'Vajilla (12p)', category: Category.KITCHEN, relevance: Relevance.HIGH, price: 60000, quantity: 1 },
  { name: 'Vasos (x6)', category: Category.KITCHEN, relevance: Relevance.HIGH, price: 15000, quantity: 1 },
  { name: 'Jarro para jugo', category: Category.KITCHEN, relevance: Relevance.LOW, price: 8000, quantity: 1 },
  { name: 'Tazas (x6)', category: Category.KITCHEN, relevance: Relevance.MEDIUM, price: 18000, quantity: 1 },
  { name: 'Juego de Cubiertos', category: Category.KITCHEN, relevance: Relevance.HIGH, price: 30000, quantity: 1 },
  { name: 'Colador', category: Category.KITCHEN, relevance: Relevance.LOW, price: 5000, quantity: 1 },
  { name: 'Paños de cocina', category: Category.KITCHEN, relevance: Relevance.HIGH, price: 7000, quantity: 1 },
  { name: 'Abre latas', category: Category.KITCHEN, relevance: Relevance.LOW, price: 4000, quantity: 1 },
  { name: 'Set de Cuchillos', category: Category.KITCHEN, relevance: Relevance.HIGH, price: 35000, quantity: 1 },
  { name: 'Freidora de aire', category: Category.KITCHEN, relevance: Relevance.LOW, price: 60000, quantity: 1 },
  { name: 'Tostador de pan', category: Category.KITCHEN, relevance: Relevance.HIGH, price: 20000, quantity: 1 },
  { name: 'Escobillon y Pala', category: Category.KITCHEN, relevance: Relevance.HIGH, price: 10000, quantity: 1 },
  { name: 'Trapeador', category: Category.KITCHEN, relevance: Relevance.HIGH, price: 12000, quantity: 1 },
  { name: 'Cafetera', category: Category.KITCHEN, relevance: Relevance.LOW, price: 50000, quantity: 1 },
  { name: 'Secador de loza', category: Category.KITCHEN, relevance: Relevance.MEDIUM, price: 15000, quantity: 1 },
  { name: '3 sillas altas de cocina americana', category: Category.KITCHEN, relevance: Relevance.MEDIUM, price: 90000, quantity: 1 },
  { name: 'Dispensador de lavaloza', category: Category.KITCHEN, relevance: Relevance.MEDIUM, price: 8000, quantity: 1 },
  { name: 'Dispensador de jabon', category: Category.KITCHEN, relevance: Relevance.MEDIUM, price: 8000, quantity: 1 },
  { name: 'Porta Esponja', category: Category.KITCHEN, relevance: Relevance.MEDIUM, price: 5000, quantity: 1 },
  { name: 'Porta servilleta', category: Category.KITCHEN, relevance: Relevance.MEDIUM, price: 6000, quantity: 1 },
  { name: 'Porta Toalla absorbente', category: Category.KITCHEN, relevance: Relevance.MEDIUM, price: 10000, quantity: 1 },
  { name: 'Licuadora', category: Category.KITCHEN, relevance: Relevance.MEDIUM, price: 45000, quantity: 1 },
  { name: 'Set de Tupperware', category: Category.KITCHEN, relevance: Relevance.HIGH, price: 20000, quantity: 1 },
  { name: 'Tabla para picar (x2)', category: Category.KITCHEN, relevance: Relevance.HIGH, price: 12000, quantity: 1 },
  // LIVING
  { name: 'Sofa en L', category: Category.LIVING, relevance: Relevance.MEDIUM, price: 600000, quantity: 1 },
  { name: '2 Sillones individuales', category: Category.LIVING, relevance: Relevance.LOW, price: 250000, quantity: 1 },
  { name: 'Mesa de Centro', category: Category.LIVING, relevance: Relevance.LOW, price: 80000, quantity: 1 },
  { name: 'TV 55"', category: Category.LIVING, relevance: Relevance.MEDIUM, price: 350000, quantity: 1 },
  { name: 'Mueble para TV', category: Category.LIVING, relevance: Relevance.MEDIUM, price: 120000, quantity: 1 },
  { name: 'Alfombra', category: Category.LIVING, relevance: Relevance.MEDIUM, price: 90000, quantity: 1 },
  { name: 'Mesa Lateral', category: Category.LIVING, relevance: Relevance.LOW, price: 40000, quantity: 1 },
  { name: 'Cojines Decorativos (x4)', category: Category.LIVING, relevance: Relevance.LOW, price: 30000, quantity: 1 },
  { name: 'Manta para Sofá', category: Category.LIVING, relevance: Relevance.LOW, price: 25000, quantity: 1 },
  // COMEDOR
  { name: 'Comedor 6 sillas', category: Category.DINING, relevance: Relevance.MEDIUM, price: 300000, quantity: 1 },
  { name: 'Florero', category: Category.DINING, relevance: Relevance.LOW, price: 15000, quantity: 1 },
  { name: 'Camino de mesa', category: Category.DINING, relevance: Relevance.LOW, price: 12000, quantity: 1 },
  { name: 'Individuales para mesa (x6)', category: Category.DINING, relevance: Relevance.LOW, price: 18000, quantity: 1 },
  // DORMITORIO PIPE
  { name: 'Cama 1.5 plazas', category: Category.PIPE_BEDROOM, relevance: Relevance.HIGH, price: 200000, quantity: 1 },
  { name: '2 juegos de sabanas 1.5p', category: Category.PIPE_BEDROOM, relevance: Relevance.HIGH, price: 50000, quantity: 1 },
  { name: '2 cubrecamas 1.5p', category: Category.PIPE_BEDROOM, relevance: Relevance.HIGH, price: 70000, quantity: 1 },
  { name: 'Basurero', category: Category.PIPE_BEDROOM, relevance: Relevance.LOW, price: 8000, quantity: 1 },
  { name: 'Escritorio', category: Category.PIPE_BEDROOM, relevance: Relevance.HIGH, price: 90000, quantity: 1 },
  { name: 'Silla de escritorio', category: Category.PIPE_BEDROOM, relevance: Relevance.HIGH, price: 60000, quantity: 1 },
  { name: 'Cortina', category: Category.PIPE_BEDROOM, relevance: Relevance.HIGH, price: 45000, quantity: 1 },
  { name: 'Lampara de escritorio', category: Category.PIPE_BEDROOM, relevance: Relevance.MEDIUM, price: 20000, quantity: 1 },
  { name: 'Velador', category: Category.PIPE_BEDROOM, relevance: Relevance.HIGH, price: 40000, quantity: 1 },
  // DORMITORIO PRINCIPAL
  { name: 'Cama 2 plazas', category: Category.MAIN_BEDROOM, relevance: Relevance.HIGH, price: 350000, quantity: 1 },
  { name: '2 juegos de sabanas 2p', category: Category.MAIN_BEDROOM, relevance: Relevance.HIGH, price: 70000, quantity: 1 },
  { name: 'Cubrecama 2p', category: Category.MAIN_BEDROOM, relevance: Relevance.HIGH, price: 50000, quantity: 1 },
  { name: 'Almohadas (x2)', category: Category.MAIN_BEDROOM, relevance: Relevance.HIGH, price: 30000, quantity: 1 },
  { name: 'Velador (x2)', category: Category.MAIN_BEDROOM, relevance: Relevance.MEDIUM, price: 80000, quantity: 1 },
  { name: 'Lampara de velador (x2)', category: Category.MAIN_BEDROOM, relevance: Relevance.MEDIUM, price: 40000, quantity: 1 },
  { name: 'Cortinas Roller duo', category: Category.MAIN_BEDROOM, relevance: Relevance.HIGH, price: 80000, quantity: 1 },
  { name: 'Cómoda / Cajonera', category: Category.MAIN_BEDROOM, relevance: Relevance.MEDIUM, price: 120000, quantity: 1 },
  // BAÑOS
  { name: 'Toallas de corpo (x4)', category: Category.BATHROOMS, relevance: Relevance.HIGH, price: 40000, quantity: 1 },
  { name: 'Toallas de mano (x4)', category: Category.BATHROOMS, relevance: Relevance.HIGH, price: 20000, quantity: 1 },
  { name: 'Set dispensadores (jabon, shampoo, acond.)', category: Category.BATHROOMS, relevance: Relevance.HIGH, price: 25000, quantity: 1 },
  { name: 'Set de baño (escobilla, basurero)', category: Category.BATHROOMS, relevance: Relevance.HIGH, price: 30000, quantity: 1 },
  { name: 'Porta Toallas', category: Category.BATHROOMS, relevance: Relevance.MEDIUM, price: 20000, quantity: 1 },
  { name: 'Salida de ducha', category: Category.BATHROOMS, relevance: Relevance.HIGH, price: 15000, quantity: 1 },
  { name: 'Antideslizante ducha', category: Category.BATHROOMS, relevance: Relevance.HIGH, price: 10000, quantity: 1 },
  { name: 'Cortina de baño y forro', category: Category.BATHROOMS, relevance: Relevance.HIGH, price: 20000, quantity: 1 },
  { name: 'Sopapo', category: Category.BATHROOMS, relevance: Relevance.HIGH, price: 5000, quantity: 1 },
  // OTROS
  { name: 'Aspiradora', category: Category.OTHER, relevance: Relevance.MEDIUM, price: 100000, quantity: 1 },
  { name: 'Set de ampolletas LED', category: Category.OTHER, relevance: Relevance.HIGH, price: 25000, quantity: 1 },
  { name: 'Arrimo para entrada', category: Category.OTHER, relevance: Relevance.LOW, price: 70000, quantity: 1 },
  { name: 'Espejo cuerpo completo', category: Category.OTHER, relevance: Relevance.LOW, price: 50000, quantity: 1 },
  { name: 'Set de herramientas básico', category: Category.OTHER, relevance: Relevance.MEDIUM, price: 30000, quantity: 1 },
  { name: 'Alargador / Zapatilla eléctrica (x3)', category: Category.OTHER, relevance: Relevance.HIGH, price: 15000, quantity: 1 },
  // TERRAZA 1
  { name: 'Barra con 2 pisos', category: Category.TERRACE_1, relevance: Relevance.LOW, price: 120000, quantity: 1 },
  // TERRAZA 2
  { name: 'Juego de terraza (2 sillas y mesa)', category: Category.TERRACE_2, relevance: Relevance.LOW, price: 150000, quantity: 1 },
  { name: 'Planta decorativa', category: Category.TERRACE_2, relevance: Relevance.LOW, price: 30000, quantity: 1 },
];